package com.jonathan.controller;

/**
 * Basic integration tests for esubscription-service  application.
 * @since 2018/06/18
 * @version 0.0.1-SNAPSHOT
 * @author Jonathan Nmaju
 */



import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
//import static org.springframework.web.bind.annotation.RequestMethod.POST;

import com.jonathan.dal.UserRepository;
import com.jonathan.model.User;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;






@RestController    // Annotation: This means that this class is a Controller
@RequestMapping(path="/subscribe", method = GET) // URL endpoint
public class MainController {
	
	private static final Logger logger = LoggerFactory.getLogger(MainController.class);
	
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	/**
	 * Welcome message
	 * @return String
	 */
	
	
	@GetMapping(path="/")
	public String main() {   
		 return "Welcome Subscription service"; 
	}
	
	
	/**
	 * Create a new Subscription: firstName and gender are optional
	 * @param consent
	 * @param gender
	 * @param dateOfBirth
	 * @param email
	 * @param subscriptionHash
	 * @param firstName
	 * 
	 * 
	 * @return integer
	 */
	
	@GetMapping(path="/new") // Map ONLY GET Requests
	public @ResponseBody int newUser (@RequestParam  char consent, @RequestParam char gender 
			, @RequestParam Date dateOfBirth, @RequestParam String email,
			 @RequestParam String firstName) {
		
		logger.debug("Saving New subscription  ");
		
		User user = new User();
	
		
		
		//Persist User
		
		try {
			
			user.setEmail(email);
			user.setFirstName(firstName);
			user.setConsent(consent);
			user.setGender(gender);
			user.setDateOfBirth(dateOfBirth);
			userRepository.save(user);  //Save User in repository
			
			
		}catch(Exception e) {
			logger.error(e.getMessage());
		}
		
		logger.debug("New subscription saved ");
		
		return user.getId();
	}
	
	
	
	
	
	/**
	 *  List all subscriptions Created
	 * @return  Iterable<User>
	 */
	@GetMapping(path="/users")
	public @ResponseBody Iterable<User> getAllUsers() {
		logger.debug("Finding all users ");
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	
	
	
	
	
}
